name: patch-test

on:
  schedule:
    - cron:  '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: build image
      run: docker build . -f Dockerfile.patchonly
